# Generated by Django 5.2.14 on 2026-05-27 02:27

import django.core.validators
import django.db.models.deletion
import learning.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('content_type', models.CharField(choices=[('markdown', 'Markdown'), ('text', 'Text'), ('pdf', 'PDF'), ('docx', 'DOCX'), ('pptx', 'PPTX')], default='markdown', max_length=20)),
                ('markdown_content', models.TextField(blank=True)),
                ('extracted_text', models.TextField(blank=True)),
                ('module_file', models.FileField(blank=True, null=True, upload_to=learning.models.module_file_upload_path)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('is_favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('markdown_content', models.TextField(blank=True)),
                ('extracted_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='learning.module')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ReadingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_percentage', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('last_position', models.CharField(blank=True, max_length=255)),
                ('last_read_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('reading', 'Reading'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reading_progress', to='learning.chapter')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_progress', to='learning.module')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_read_at'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='module',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='learning.subject'),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('color', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BoardScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=learning.models.board_scan_upload_path)),
                ('raw_ocr_text', models.TextField(blank=True)),
                ('cleaned_text', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('review_status', models.CharField(choices=[('new', 'New'), ('needs_review', 'Needs review'), ('reviewed', 'Reviewed'), ('mastered', 'Mastered')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_scans', to=settings.AUTH_USER_MODEL)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='board_scans', to='learning.chapter')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='board_scans', to='learning.module')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='board_scans', to='learning.subject')),
                ('tags', models.ManyToManyField(blank=True, related_name='board_scans', to='learning.tag')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='chapter',
            index=models.Index(fields=['owner', 'module', 'order'], name='learning_ch_owner_i_7652f6_idx'),
        ),
        migrations.AddIndex(
            model_name='readingprogress',
            index=models.Index(fields=['owner', 'module', 'chapter'], name='learning_re_owner_i_33055c_idx'),
        ),
        migrations.AddIndex(
            model_name='readingprogress',
            index=models.Index(fields=['owner', 'status'], name='learning_re_owner_i_e55399_idx'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('owner', 'title'), name='unique_subject_title_per_owner'),
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['owner', 'subject'], name='learning_mo_owner_i_4e0fd9_idx'),
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['content_type'], name='learning_mo_content_799862_idx'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_tag_name_per_owner'),
        ),
        migrations.AddIndex(
            model_name='boardscan',
            index=models.Index(fields=['owner', 'review_status'], name='learning_bo_owner_i_d9f4ef_idx'),
        ),
        migrations.AddIndex(
            model_name='boardscan',
            index=models.Index(fields=['owner', 'subject'], name='learning_bo_owner_i_096ca4_idx'),
        ),
        migrations.AddIndex(
            model_name='boardscan',
            index=models.Index(fields=['owner', 'module'], name='learning_bo_owner_i_28ab5f_idx'),
        ),
    ]
