# Generated by Django 5.2.15 on 2026-06-05 10:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('task_type', models.CharField(choices=[('task', 'Task'), ('deadline', 'Deadline'), ('quiz', 'Quiz'), ('project', 'Project'), ('reading', 'Reading')], default='task', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='learning.chapter')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='learning.module')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_tasks', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='learning.subject')),
            ],
            options={
                'ordering': ['due_at', '-created_at'],
                'indexes': [models.Index(fields=['owner', 'subject'], name='learning_ac_owner_i_d12657_idx'), models.Index(fields=['owner', 'status'], name='learning_ac_owner_i_7d3292_idx'), models.Index(fields=['owner', 'task_type'], name='learning_ac_owner_i_dae9ba_idx'), models.Index(fields=['owner', 'due_at'], name='learning_ac_owner_i_438c9d_idx')],
            },
        ),
        migrations.CreateModel(
            name='SubjectPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('post_type', models.CharField(choices=[('announcement', 'Announcement'), ('reminder', 'Reminder'), ('deadline', 'Deadline'), ('update', 'Update')], default='announcement', max_length=20)),
                ('posted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_posts', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='learning.subject')),
            ],
            options={
                'ordering': ['-is_pinned', '-posted_at', '-created_at'],
                'indexes': [models.Index(fields=['owner', 'subject'], name='learning_su_owner_i_68832c_idx'), models.Index(fields=['owner', 'post_type'], name='learning_su_owner_i_64f4fd_idx'), models.Index(fields=['owner', 'is_pinned'], name='learning_su_owner_i_05d3f3_idx'), models.Index(fields=['owner', 'posted_at'], name='learning_su_owner_i_80629e_idx')],
            },
        ),
    ]
