# Generated by Django 5.2.15 on 2026-06-05 10:46

from django.conf import settings
from django.db import migrations, models
from django.db.models import Count


def dedupe_reading_progress(apps, schema_editor):
    ReadingProgress = apps.get_model("learning", "ReadingProgress")
    duplicates = (
        ReadingProgress.objects.values("owner_id", "module_id", "chapter_id")
        .annotate(row_count=Count("id"))
        .filter(row_count__gt=1)
    )

    for duplicate in duplicates:
        rows = ReadingProgress.objects.filter(
            owner_id=duplicate["owner_id"],
            module_id=duplicate["module_id"],
            chapter_id=duplicate["chapter_id"],
        ).order_by("-last_read_at", "-id")
        keep = rows.first()
        rows.exclude(id=keep.id).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_academictask_subjectpost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(dedupe_reading_progress, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='readingprogress',
            constraint=models.UniqueConstraint(fields=('owner', 'module', 'chapter'), name='unique_reading_progress_per_target', nulls_distinct=False),
        ),
    ]
