# Generated by Django 6.0.6 on 2026-06-25 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_remove_academic_tasks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True)),
                ('task_type', models.CharField(choices=[('note', 'Note'), ('reminder', 'Reminder'), ('todo', 'To-Do')], default='note', max_length=20)),
                ('is_completed', models.BooleanField(default=False)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_pinned', 'is_completed', '-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='subjectpost',
            name='learning_su_owner_i_68832c_idx',
        ),
        migrations.RemoveIndex(
            model_name='subjectpost',
            name='learning_su_owner_i_64f4fd_idx',
        ),
        migrations.RemoveIndex(
            model_name='subjectpost',
            name='learning_su_owner_i_05d3f3_idx',
        ),
        migrations.RemoveIndex(
            model_name='subjectpost',
            name='learning_su_owner_i_80629e_idx',
        ),
        migrations.AddField(
            model_name='studytask',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studytask',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='learning.subject'),
        ),
        migrations.RemoveField(
            model_name='subjectpost',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='subjectpost',
            name='subject',
        ),
        migrations.AddIndex(
            model_name='studytask',
            index=models.Index(fields=['owner', 'subject'], name='learning_st_owner_i_53fa06_idx'),
        ),
        migrations.AddIndex(
            model_name='studytask',
            index=models.Index(fields=['owner', 'task_type'], name='learning_st_owner_i_e1ad36_idx'),
        ),
        migrations.AddIndex(
            model_name='studytask',
            index=models.Index(fields=['owner', 'is_pinned'], name='learning_st_owner_i_2b6811_idx'),
        ),
        migrations.AddIndex(
            model_name='studytask',
            index=models.Index(fields=['owner', 'is_completed'], name='learning_st_owner_i_735eec_idx'),
        ),
        migrations.DeleteModel(
            name='SubjectPost',
        ),
    ]
