# Generated by Django 5.2.14 on 2026-05-27 02:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('mastered', 'Mastered'), ('needs_review', 'Needs review'), ('abandoned', 'Abandoned')], default='in_progress', max_length=20)),
                ('clear_answers_count', models.PositiveSmallIntegerField(default=0)),
                ('target_clear_answers', models.PositiveSmallIntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('board_scan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutor_sessions', to='learning.boardscan')),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutor_sessions', to='learning.chapter')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutor_sessions', to='learning.module')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TutorMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('system', 'System'), ('assistant', 'Assistant'), ('user', 'User')], max_length=20)),
                ('content', models.TextField()),
                ('clarity_result', models.CharField(blank=True, choices=[('clear', 'Clear'), ('unclear', 'Unclear'), ('partial', 'Partial')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_services.tutorsession')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='tutorsession',
            index=models.Index(fields=['owner', 'status'], name='ai_services_owner_i_70b031_idx'),
        ),
        migrations.AddIndex(
            model_name='tutorsession',
            index=models.Index(fields=['owner', 'module'], name='ai_services_owner_i_0707eb_idx'),
        ),
        migrations.AddIndex(
            model_name='tutormessage',
            index=models.Index(fields=['session', 'created_at'], name='ai_services_session_e0159a_idx'),
        ),
    ]
